package TRES;
import javax.swing.JOptionPane;

/**
 *
 * @author AA2020
 */
public class Ventana_TRES extends javax.swing.JFrame {
    Camisa camisaObj = new Camisa("Medium", "Azúl Oscuro");

    /**
     * Creates new form Ventana_TRES
     */
    public Ventana_TRES() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanFinal = new javax.swing.JPanel();
        btnInfo = new javax.swing.JButton();
        btnProbar = new javax.swing.JButton();
        btnTela = new javax.swing.JButton();
        btnEstilo = new javax.swing.JButton();
        lblImg = new javax.swing.JLabel();
        lblCamisa = new javax.swing.JLabel();
        lblPORCOMPRAR = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prisma Moda | Comprar");

        jPanFinal.setBackground(new java.awt.Color(0, 0, 0));

        btnInfo.setBackground(new java.awt.Color(0, 0, 0));
        btnInfo.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        btnInfo.setForeground(new java.awt.Color(255, 255, 255));
        btnInfo.setText("INFORMACIÓN GENERAL");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        btnProbar.setBackground(new java.awt.Color(0, 0, 0));
        btnProbar.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        btnProbar.setForeground(new java.awt.Color(255, 255, 255));
        btnProbar.setText("PROBAR");
        btnProbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProbarActionPerformed(evt);
            }
        });

        btnTela.setBackground(new java.awt.Color(0, 0, 0));
        btnTela.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        btnTela.setForeground(new java.awt.Color(255, 255, 255));
        btnTela.setText("TELA");
        btnTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaActionPerformed(evt);
            }
        });

        btnEstilo.setBackground(new java.awt.Color(0, 0, 0));
        btnEstilo.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        btnEstilo.setForeground(new java.awt.Color(255, 255, 255));
        btnEstilo.setText("ESTILO");
        btnEstilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstiloActionPerformed(evt);
            }
        });

        lblImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TRES/Imagenes/prisma.png"))); // NOI18N

        lblCamisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TRES/Imagenes/camisa.jpg"))); // NOI18N

        lblPORCOMPRAR.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        lblPORCOMPRAR.setForeground(new java.awt.Color(255, 255, 255));
        lblPORCOMPRAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPORCOMPRAR.setText("POR COMPRAR");

        javax.swing.GroupLayout jPanFinalLayout = new javax.swing.GroupLayout(jPanFinal);
        jPanFinal.setLayout(jPanFinalLayout);
        jPanFinalLayout.setHorizontalGroup(
            jPanFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanFinalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanFinalLayout.createSequentialGroup()
                        .addComponent(lblCamisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEstilo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProbar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPORCOMPRAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanFinalLayout.setVerticalGroup(
            jPanFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanFinalLayout.createSequentialGroup()
                .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCamisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanFinalLayout.createSequentialGroup()
                        .addComponent(lblPORCOMPRAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnProbar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTela)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEstilo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInfo)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        JOptionPane.showMessageDialog(this, "Color: " + camisaObj.color + "\nTalla: " + camisaObj.talla + "\nPrecio: $7.99");
    }//GEN-LAST:event_btnInfoActionPerformed

    private void btnProbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProbarActionPerformed
        JOptionPane.showMessageDialog(this, camisaObj.DressUp());
    }//GEN-LAST:event_btnProbarActionPerformed

    private void btnTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaActionPerformed
        JOptionPane.showMessageDialog(this, camisaObj.TelaType());
    }//GEN-LAST:event_btnTelaActionPerformed

    private void btnEstiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstiloActionPerformed
        JOptionPane.showMessageDialog(this, camisaObj.Style());
    }//GEN-LAST:event_btnEstiloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_TRES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_TRES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_TRES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_TRES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_TRES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEstilo;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnProbar;
    private javax.swing.JButton btnTela;
    private javax.swing.JPanel jPanFinal;
    private javax.swing.JLabel lblCamisa;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblPORCOMPRAR;
    // End of variables declaration//GEN-END:variables
}
